version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX..."
      - apt-get update -y
      - apt-get install -y nginx
  build:
    commands:
      - echo "Build started on $(date)"
      - cp index.html /var/www/html/index.html
  post_build:
    commands:
      - echo "Restarting NGINX to apply changes..."
      - systemctl restart nginx || true

artifacts:
  files:
    - index.html
